---
- hosts: all
  user: root
  roles:
  - openstack-common

- hosts: controller
  user: root
  roles:
  - openstack-database
  - openstack-messaging-server
  - openstack-keystone
  - openstack-glance
  - openstack-nova-controller

- hosts: compute-kvm
  user: root
  roles:
  - openstack-nova-compute-kvm
