---
- hosts: all
  user: root
  roles:
  - openstack-common

- hosts: controller
  user: root
  roles:
  - openstack-database
  - openstack-messaging-server
  - openstack-keystone
  - openstack-glance
  - openstack-nova-controller
  - openstack-neutron-controller

- hosts: compute-kvm
  user: root
  roles:
  - openstack-nova-compute-kvm

- hosts: network
  user: root
  roles:
  - openstack-neutron-network

- hosts: controller
  user: root
  roles:
  - openstack-external-network
