---
# - include: ../../../tasks/create-service-user.yml
#   vars:
#     username: neutron
#     password: "{{ NEUTRON_PASS }}"

- name: "Ensure the '{{ username }}' user exists"
  keystone_user: >
    user={{ username }} password={{ password }} email={{ ADMIN_EMAIL }} tenant=service
    token={{ KEYSTONE_ADMIN_TOKEN }}
    endpoint=http://{{ keystone_host }}:{{ keystone_admin_port }}/v2.0

- name: "Ensure the 'admin' role exists"
  keystone_user: >
    role=admin user={{ username }} tenant=service
    token={{ KEYSTONE_ADMIN_TOKEN }}
    endpoint=http://{{ keystone_host }}:{{ keystone_admin_port }}/v2.0
