---
- name: Ensure relavant packages are installed
  yum: "name={{ item }} state=installed"
  with_items: 
  - openstack-nova-api
  - openstack-nova-cert
  - openstack-nova-conductor
  - openstack-nova-console
  - openstack-nova-novncproxy 
  - openstack-nova-scheduler
  - python-novaclient

- name: Configure nova
  template: |
    dest=/etc/nova/nova.conf
    src=nova.conf
    backup=yes
  notify: Restart nova services

- include: ../../../tasks/create-database-and-user.yml
  vars:
    db_name: "{{ nova_db }}"
    db_user: "{{ nova_db_user }}"
    db_password: "{{ NOVA_DBPASS }}"

- name: Change ownership of all files to nova
  file: path=/etc/nova recurse=yes owner=nova group=nova state=directory

- name: DB sync for nova
  sudo: yes
  sudo_user: nova
  shell: |
    creates=/etc/nova/db.synced
    /usr/bin/nova-manage db_sync
    date >> /etc/nova/db.synced

- include: ../../../tasks/create-service-user.yml
  vars:
    username: nova
    password: "{{ NOVA_PASS }}"
  delegate_to: "{{ keystone_host }}"

- name: Create a service entry for the Compute Service
  include: ../../../tasks/keystone_service.yml
  vars:
    name: nova
    type: compute
    description: OpenStack Compute
  delegate_to: "{{ keystone_host }}"

- name: Create API endpoint for compute service
  include: ../../../tasks/api_endpoint.yml
  vars:
    service: compute
    endpoint:
      host: "{{ nova_controller_host }}"
      port: "{{ nova_controller_port }}"
      path: "/v2/%\\(tenant_id\\)s"
  delegate_to: "{{ keystone_host }}"

- name: Enable and start the nova services
  service: name={{ item }} enabled=yes state=started
  with_items: nova_services
