---
- name: Ensure relavant packages are installed
  yum: "name={{ item }} state=installed"
  with_items: 
  - openstack-nova-api
  - openstack-nova-cert
  - openstack-nova-conductor
  - openstack-nova-console
  - openstack-nova-novncproxy 
  - openstack-nova-scheduler
  - python-novaclient

- name: Configure nova
  template: |
    dest=/etc/nova/nova.conf
    src=nova.conf
    backup=yes
  notify: Restart nova services

- name: Create the nova database
  mysql_db: name={{ nova_db }} login_user=root login_password={{ MYSQL_ROOT_PASSWORD }}
- name: Ensure nova database user exist
  mysql_user: |
    name={{ nova_db_user }}
    password={{ NOVA_DBPASS }}
    host={{ item }}
    priv={{ nova_db }}.*:ALL
    login_host={{ db_host }}
    login_user=root
    login_password={{ MYSQL_ROOT_PASSWORD }}
  with_items:
  - localhost
  - "%"

- name: Change ownership of all files to nova
  file: path=/etc/nova recurse=yes owner=nova group=nova state=directory

- name: DB sync for nova
  sudo: yes
  sudo_user: nova
  shell: |
    creates=/etc/nova/db.synced
    /usr/bin/nova-manage db_sync
    date >> /etc/nova/db.synced

- name: "Ensure the 'nova' user exists"
  keystone_user: >
    user=nova password={{ NOVA_PASS }} email={{ ADMIN_EMAIL }} tenant=service
    token={{ KEYSTONE_ADMIN_TOKEN }}
    endpoint=http://{{ keystone_host }}:{{ keystone_admin_port }}/v2.0
  delegate_to: "{{ keystone_host }}"

- name: "Ensure the 'admin' role exists"
  keystone_user: >
    role=admin user=nova tenant=service
    token={{ KEYSTONE_ADMIN_TOKEN }}
    endpoint=http://{{ keystone_host }}:{{ keystone_admin_port }}/v2.0
  delegate_to: "{{ keystone_host }}"

- name: Create a service entry for the Compute Service
  include: ../../../tasks/keystone_service.yml
  vars:
    name: nova
    type: compute
    description: OpenStack Compute
  delegate_to: "{{ keystone_host }}"

- name: Create API endpoint for compute service
  include: ../../../tasks/api_endpoint.yml
  vars:
    service: compute
    endpoint:
      host: "{{ nova_controller_host }}"
      port: "{{ nova_controller_port }}"
  delegate_to: "{{ keystone_host }}"

- name: Enable and start the nova services
  service: name={{ item }} enabled=yes state=started
  with_items: nova_services
