---
- include: ../../../tasks/create-database-and-user.yml
  vars:
    db_name: "{{ neutron_db }}"
    db_user: "{{ neutron_db_user }}"
    db_password: "{{ NEUTRON_DBPASS }}"

- include: ../../../tasks/create-service-user.yml
  vars:
    username: neutron
    password: "{{ NEUTRON_PASS }}"
  delegate_to: "{{ keystone_host }}"

- name: Create a service entry for the OpenStack Networking
  include: ../../../tasks/keystone_service.yml
  vars:
    name: neutron
    type: network
    description: "OpenStack Networking"
  delegate_to: "{{ keystone_host }}"

- name: Create API endpoint for network service
  include: ../../../tasks/api_endpoint.yml
  vars:
    service: network
    endpoint:
      host: "{{ neutron_controller_host }}"
      port: "{{ neutron_controller_port }}"

- name: Ensure relavant packages are installed
  yum: "name={{ item }} state=installed"
  with_items: 
  - openstack-neutron
  - openstack-neutron-ml2
  - python-neutronclient

- name: Get Nova admin tenant ID
  shell: |
    keystone tenant-list | awk '/ service / { print $2 }'
  register: nova_admin_tenant_id
  environment: token_auth_env
  delegate_to: "{{ keystone_host }}"

- name: Configure Networking to use the database
  include: ../../../tasks/ini-settings.yml
  vars:
    file: /etc/neutron/neutron.conf
    sections:
    - name: database
      settings:
      - [ "connection", "mysql://{{ neutron_db_user }}:{{ NEUTRON_DBPASS }}@{{ db_host }}/{{ neutron_db }}" ]
  notify: Restart neutron services

- name: Configure Networking to use the identity service for authentication
  include: ../../../tasks/ini-settings.yml
  vars:
    file: /etc/neutron/neutron.conf
    sections:
    - name: DEFAULT
      settings:
      - [ "auth_strategy", "keystone" ]
    - name: keystone_authtoken
      settings:
      - [ "auth_uri", "http://{{ keystone_host }}:{{ keystone_port }}" ]
      - [ "auth_host", "{{ keystone_host }}" ]
      - [ "auth_protocol", "http" ]
      - [ "auth_port", "{{ keystone_admin_port }}" ]
      - [ "admin_tenant_name", "service" ]
      - [ "admin_user", "neutron" ]
      - [ "admin_password", "{{ NEUTRON_PASS }}" ]
  notify: Restart neutron services

- name: Configure Networking to use the message broker
  include: ../../../tasks/ini-settings.yml
  vars:
    file: /etc/neutron/neutron.conf
    sections:
    - name: DEFAULT
      settings:
      - [ "rpc_backend", "neutron.openstack.common.rpc.impl_qpid" ]
      - [ "qpid_hostname", "{{ keystone_host }}" ]
  notify: Restart neutron services

- name: Configure Networking to notify Compute about network topology changes
  include: ../../../tasks/ini-settings.yml
  vars:
    file: /etc/neutron/neutron.conf
    sections:
    - name: DEFAULT
      settings:
      - [ "notify_nova_on_port_status_changes", "True" ]
      - [ "notify_nova_on_port_data_changes", "True" ]
      - [ "nova_url", "http://{{ nova_controller_host }}:8774/v2" ]
      - [ "nova_admin_username", "nova" ]
      - [ "nova_admin_tenant_id", "{{ nova_admin_tenant_id.stdout }}" ]
      - [ "nova_admin_password", "{{ NOVA_PASS }}" ]
      - [ "nova_admin_auth_url", "http://{{ keystone_host }}:{{ keystone_admin_port }}/v2.0" ]
  notify: Restart neutron services

- name: Configure Networking to use the Modular Layer 2 (ML2) plug-in and associated services
  include: ../../../tasks/ini-settings.yml
  vars:
    file: /etc/neutron/neutron.conf
    sections:
    - name: DEFAULT
      settings:
      - [ "core_plugin", "ml2" ]
      - [ "service_plugins", "router" ]
  notify: Restart neutron services

- name: Configure the ML2 plug-in
  include: ../../../tasks/ini-settings.yml
  vars:
    file: /etc/neutron/plugins/ml2/ml2_conf.ini
    sections:
    - name: ml2
      settings: 
      - [ "type_drivers", "gre" ]
      - [ "tenant_network_types", "gre" ]
      - [ "mechanism_drivers", "openvswitch" ]
    - name: ml2_type_gre
      settings: 
      - [ "tunnel_id_ranges", "1:1000" ]
    - name: securitygroup
      settings: 
      - [ "firewall_driver", "neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver" ]
      - [ "enable_security_group", "True" ]
  notify: Restart neutron services

- name: Ensure symlink to plug-in configuration
  file: path=/etc/neutron/plugin.ini state=link src=/etc/neutron/plugins/ml2/ml2_conf.ini

- name: Enable and start neutron services
  service: name=neutron-server enabled=yes state=started
