---
- name: Create the neutron database
  mysql_db: name={{ neutron_db }} login_user=root login_password={{ MYSQL_ROOT_PASSWORD }}
- name: Ensure neutron database user exist
  mysql_user: |
    name={{ neutron_db_user }}
    password={{ NEUTRON_DBPASS }}
    host={{ item }}
    priv={{ neutron_db }}.*:ALL
    login_host={{ db_host }}
    login_user=root
    login_password={{ MYSQL_ROOT_PASSWORD }}
  with_items:
  - localhost
  - "%"

- name: "Ensure the 'neutron' user exists"
  keystone_user: >
    user=neutron password={{ NEUTRON_PASS }} email={{ ADMIN_EMAIL }} tenant=service
    token={{ KEYSTONE_ADMIN_TOKEN }}
    endpoint=http://{{ keystone_host }}:{{ keystone_admin_port }}/v2.0
  delegate_to: "{{ keystone_host }}"

- name: "Ensure the 'admin' role exists"
  keystone_user: >
    role=admin user=neutron tenant=service
    token={{ KEYSTONE_ADMIN_TOKEN }}
    endpoint=http://{{ keystone_host }}:{{ keystone_admin_port }}/v2.0
  delegate_to: "{{ keystone_host }}"

- name: Create a service entry for the OpenStack Networking
  shell: |
    export OS_SERVICE_TOKEN={{ KEYSTONE_ADMIN_TOKEN }}
    export OS_SERVICE_ENDPOINT=http://{{ keystone_host }}:{{ keystone_admin_port }}/v2.0
    if ! keystone service-get neutron
    then 
      keystone service-create --name=neutron --type=network --description="OpenStack Networking"
    fi
  delegate_to: "{{ keystone_host }}"

- name: Check OpenStack Networking API endpoint exists
  shell: "keystone --os-username=admin --os-password={{ ADMIN_PASS }} --os-auth-url=http://{{ keystone_host }}:{{ keystone_admin_port }}/v2.0 --os-tenant-name=admin endpoint-get --service=network"
  register: check_endpoint_result
  ignore_errors: True
  delegate_to: "{{ keystone_host }}"

- name: Specify API endpoints for network service
  when: check_endpoint_result.rc != 0
  shell: |
    export OS_SERVICE_TOKEN={{ KEYSTONE_ADMIN_TOKEN }}
    export OS_SERVICE_ENDPOINT=http://{{ keystone_host }}:{{ keystone_admin_port }}/v2.0
    export SERVICE_ID=$(keystone service-list | awk '/ network / {print $2}')
    keystone endpoint-create --service-id=${SERVICE_ID} --publicurl=http://{{ neutron_controller_host }}:{{ neutron_controller_port }}/v2.0/%\(tenant_id\)s --internalurl=http://{{ neutron_controller_host }}:{{ neutron_controller_port }}/v2.0/%\(tenant_id\)s --adminurl=http://{{ neutron_controller_host }}:{{ neutron_controller_port }}/v2.0/%\(tenant_id\)s
  delegate_to: "{{ keystone_host }}"
