---
- name: External network
  quantum_network: >
    name=ext-net
    state=present
    shared=true
    router_external=yes
    provider_network_type=gre
    provider_segmentation_id=1
    auth_url=http://{{ keystone_host }}:{{ keystone_admin_port }}/v2.0
    login_username=admin
    login_password={{ ADMIN_PASS }}
    login_tenant_name=admin

- quantum_subnet: >
    name=ext-subnet
    network_name=ext-net
    tenant_name=admin
    state=present
    allocation_pool_start=203.0.113.101
    allocation_pool_end=203.0.113.200
    cidr=203.0.113.0/24
    enable_dhcp=False
    gateway_ip=203.0.113.1
    login_username=admin
    login_password={{ ADMIN_PASS }}
    login_tenant_name=admin
