---
- name: Ensure relavant packages are installed
  yum: "name={{ item }} state=installed"
  with_items: 
  - openstack-glance 
  - python-glanceclient

- name: Configure glance-api
  template: |
    dest=/etc/glance/glance-api.conf
    src=glance-api.conf
    backup=yes
  notify: Restart glance-api service

- name: Configure glance-registry
  template: |
    dest=/etc/glance/glance-registry.conf
    src=glance-registry.conf
    backup=yes
  notify: Restart glance-registry service

- include: ../../../tasks/create-database-and-user.yml
  vars:
    db_name: "{{ glance_db }}"
    db_user: "{{ glance_db_user }}"
    db_password: "{{ GLANCE_DBPASS }}"

- name: Change ownership of all files to glance
  file: path=/etc/glance recurse=yes owner=glance group=glance state=directory

- name: DB sync for glance
  sudo: yes
  sudo_user: glance
  shell: |
    creates=/etc/glance/db.synced
    /usr/bin/glance-manage db_sync
    date >> /etc/glance/db.synced

- name: "Ensure the 'glance' user exists"
  keystone_user: >
    user=glance password={{ GLANCE_PASS }} email={{ ADMIN_EMAIL }} tenant=service
    token={{ KEYSTONE_ADMIN_TOKEN }}
    endpoint=http://{{ keystone_host }}:{{ keystone_admin_port }}/v2.0
  delegate_to: "{{ keystone_host }}"

- name: "Ensure the 'admin' role exists"
  keystone_user: >
    role=admin user=glance tenant=service
    token={{ KEYSTONE_ADMIN_TOKEN }}
    endpoint=http://{{ keystone_host }}:{{ keystone_admin_port }}/v2.0
  delegate_to: "{{ keystone_host }}"

- name: Create a service entry for the OpenStack Image Service
  include: ../../../tasks/keystone_service.yml
  vars:
    name: glance
    type: image
    description: OpenStack Image Service

- name: Create API endpoint for image service
  include: ../../../tasks/api_endpoint.yml
  vars:
    service: image
    endpoint:
      host: "{{ glance_host }}"
      port: "{{ glance_port }}"
  delegate_to: "{{ keystone_host }}"

- name: Enable and start the image services
  service: name={{ item }} enabled=yes state=started
  with_items:
  - openstack-glance-api
  - openstack-glance-registry
